const mongoose = require("mongoose");

const cartSchema = mongoose.Schema({
  code: String,
  name: String,
  description: String,
  sapProductName: String,
  sellingAttributes: Array,
  color: Object,
  whitePrice: Object,
  priceType: String,
  importedBy: String,
  importedDate: String,
  netQuantity: String,
  countryOfProduction: String,
  productTypeName: String,
  measurements: Array,
  lengthCollection: Array,
  fits: Array,
  showPriceMarker: Boolean,
  keyFibreTypes: Array,
  baseProductCode: String,
  ancestorProductCode: String,
  mainCategory: Object,
  supercategories: Array,
  constructionDescr: String,
  customerGroup: String,
  functions: Array,
  newArrival: Boolean,
  articlesList: Array,
  inStock: String,
  productUrl: String,
  swatchesType: String,
  rootCategoryPath: String,
  productKey: String,
  productCountryOfProduction: String,
  showGarmentsInfo: Boolean,
  yearOfProduction: String,
  styleCollection: Array,
  materialDetails: Array,
  presentationTypes: String,
  multipack: Boolean,
  newProduct: Boolean,
  authorID: String,
  quantity: { type: Number, default: 1 },
});

const CartModel = mongoose.model("cart", cartSchema);

module.exports = {
  CartModel,
}